export {
  followTypeSchema,
  followRecordBaseSchema,
  followRecordSchema,
  createFollowRecordSchema,
  updateFollowRecordSchema,
  followTypeMap,
  getFollowTypeLabel,
  followTypeLegacySchema,
  toFollowType,
  toFollowTypeLegacy,
  type FollowType,
  type FollowRecordBase,
  type FollowRecord,
  type FollowTypeLegacy,
} from './follow-record.schema'
