/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateCustomerDto,
  CustomerControllerFindAllParams,
  LoginDto,
  RegisterDto,
  UpdateCustomerDto
} from '../models';

import { customInstance } from './mutator';



  export const getScrmApi = () => {
const healthControllerCheck = (
    
 ) => {
      return customInstance<void>(
      {url: `/health`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 用户登录
 */
const authControllerLogin = (
    loginDto: LoginDto,
 ) => {
      return customInstance<void>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto
    },
      );
    }
  
/**
 * @summary 用户注册
 */
const authControllerRegister = (
    registerDto: RegisterDto,
 ) => {
      return customInstance<void>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerDto
    },
      );
    }
  
/**
 * @summary 获取当前用户信息
 */
const authControllerGetUserInfo = (
    
 ) => {
      return customInstance<void>(
      {url: `/auth/me`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 创建客户
 */
const customerControllerCreate = (
    createCustomerDto: CreateCustomerDto,
 ) => {
      return customInstance<void>(
      {url: `/customers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCustomerDto
    },
      );
    }
  
/**
 * @summary 获取客户列表
 */
const customerControllerFindAll = (
    params?: CustomerControllerFindAllParams,
 ) => {
      return customInstance<void>(
      {url: `/customers`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary 获取客户详情
 */
const customerControllerFindOne = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/customers/${id}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary 更新客户
 */
const customerControllerUpdate = (
    id: string,
    updateCustomerDto: UpdateCustomerDto,
 ) => {
      return customInstance<void>(
      {url: `/customers/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateCustomerDto
    },
      );
    }
  
/**
 * @summary 删除客户
 */
const customerControllerRemove = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/customers/${id}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary 分配客户
 */
const customerControllerAssign = (
    
 ) => {
      return customInstance<void>(
      {url: `/customers/assign`, method: 'POST'
    },
      );
    }
  
return {healthControllerCheck,authControllerLogin,authControllerRegister,authControllerGetUserInfo,customerControllerCreate,customerControllerFindAll,customerControllerFindOne,customerControllerUpdate,customerControllerRemove,customerControllerAssign}};
export type HealthControllerCheckResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getScrmApi>['healthControllerCheck']>>>
export type AuthControllerLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getScrmApi>['authControllerLogin']>>>
export type AuthControllerRegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getScrmApi>['authControllerRegister']>>>
export type AuthControllerGetUserInfoResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getScrmApi>['authControllerGetUserInfo']>>>
export type CustomerControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getScrmApi>['customerControllerCreate']>>>
export type CustomerControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getScrmApi>['customerControllerFindAll']>>>
export type CustomerControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getScrmApi>['customerControllerFindOne']>>>
export type CustomerControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getScrmApi>['customerControllerUpdate']>>>
export type CustomerControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getScrmApi>['customerControllerRemove']>>>
export type CustomerControllerAssignResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getScrmApi>['customerControllerAssign']>>>
