/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  AutomationControllerGetNotificationsParams,
  AutomationControllerGetTaskHistoryParams,
  CreateAutomationRuleDto,
  UpdateAutomationRuleDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getAutomation = () => {
  /**
   * @summary 创建自动化规则
   */
  const automationControllerCreateRule = (
    createAutomationRuleDto: CreateAutomationRuleDto,
  ) => {
    return customInstance<void>({
      url: `/automation/rules`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createAutomationRuleDto,
    });
  };
  /**
   * @summary 查询所有自动化规则
   */
  const automationControllerFindAllRules = () => {
    return customInstance<void>({ url: `/automation/rules`, method: "GET" });
  };
  /**
   * @summary 查询单个规则
   */
  const automationControllerFindOneRule = (id: string) => {
    return customInstance<void>({
      url: `/automation/rules/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 更新规则
   */
  const automationControllerUpdateRule = (
    id: string,
    updateAutomationRuleDto: UpdateAutomationRuleDto,
  ) => {
    return customInstance<void>({
      url: `/automation/rules/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateAutomationRuleDto,
    });
  };
  /**
   * @summary 删除规则
   */
  const automationControllerRemoveRule = (id: string) => {
    return customInstance<void>({
      url: `/automation/rules/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 启用/禁用规则
   */
  const automationControllerToggleEnabled = (id: string) => {
    return customInstance<void>({
      url: `/automation/rules/${id}/toggle`,
      method: "PATCH",
    });
  };
  /**
   * @summary 手动触发规则
   */
  const automationControllerTriggerRule = (id: string) => {
    return customInstance<void>({
      url: `/automation/rules/${id}/trigger`,
      method: "POST",
    });
  };
  /**
   * @summary 查询任务执行历史
   */
  const automationControllerGetTaskHistory = (
    params: AutomationControllerGetTaskHistoryParams,
  ) => {
    return customInstance<void>({
      url: `/automation/tasks/history`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 查询当前用户通知
   */
  const automationControllerGetNotifications = (
    params: AutomationControllerGetNotificationsParams,
  ) => {
    return customInstance<void>({
      url: `/automation/notifications`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 标记通知为已读
   */
  const automationControllerMarkNotificationAsRead = (id: string) => {
    return customInstance<void>({
      url: `/automation/notifications/${id}/read`,
      method: "PATCH",
    });
  };
  /**
   * @summary 标记所有通知为已读
   */
  const automationControllerMarkAllNotificationsAsRead = () => {
    return customInstance<void>({
      url: `/automation/notifications/read-all`,
      method: "PATCH",
    });
  };
  return {
    automationControllerCreateRule,
    automationControllerFindAllRules,
    automationControllerFindOneRule,
    automationControllerUpdateRule,
    automationControllerRemoveRule,
    automationControllerToggleEnabled,
    automationControllerTriggerRule,
    automationControllerGetTaskHistory,
    automationControllerGetNotifications,
    automationControllerMarkNotificationAsRead,
    automationControllerMarkAllNotificationsAsRead,
  };
};
export type AutomationControllerCreateRuleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAutomation>["automationControllerCreateRule"]
    >
  >
>;
export type AutomationControllerFindAllRulesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAutomation>["automationControllerFindAllRules"]
    >
  >
>;
export type AutomationControllerFindOneRuleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAutomation>["automationControllerFindOneRule"]
    >
  >
>;
export type AutomationControllerUpdateRuleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAutomation>["automationControllerUpdateRule"]
    >
  >
>;
export type AutomationControllerRemoveRuleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAutomation>["automationControllerRemoveRule"]
    >
  >
>;
export type AutomationControllerToggleEnabledResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAutomation>["automationControllerToggleEnabled"]
    >
  >
>;
export type AutomationControllerTriggerRuleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAutomation>["automationControllerTriggerRule"]
    >
  >
>;
export type AutomationControllerGetTaskHistoryResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAutomation>["automationControllerGetTaskHistory"]
    >
  >
>;
export type AutomationControllerGetNotificationsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAutomation>["automationControllerGetNotifications"]
    >
  >
>;
export type AutomationControllerMarkNotificationAsReadResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAutomation
      >["automationControllerMarkNotificationAsRead"]
    >
  >
>;
export type AutomationControllerMarkAllNotificationsAsReadResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAutomation
      >["automationControllerMarkAllNotificationsAsRead"]
    >
  >
>;
