/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CmsControllerFindAllContentsParams,
  CmsControllerGetArticlesParams,
  CmsControllerGetCasesParams,
  CmsControllerGetProductShowcasesParams,
  CmsControllerGetProfilesParams,
  CreateCmsContentDto,
  CreateCmsTagDto,
  UpdateCmsContentDto,
  UpdateCmsTagDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getCms = () => {
  /**
   * @summary 创建内容
   */
  const cmsControllerCreateContent = (
    createCmsContentDto: CreateCmsContentDto,
  ) => {
    return customInstance<void>({
      url: `/cms/contents`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCmsContentDto,
    });
  };
  /**
   * @summary 获取内容列表
   */
  const cmsControllerFindAllContents = (
    params?: CmsControllerFindAllContentsParams,
  ) => {
    return customInstance<void>({
      url: `/cms/contents`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取内容详情
   */
  const cmsControllerFindOneContent = (id: string) => {
    return customInstance<void>({ url: `/cms/contents/${id}`, method: "GET" });
  };
  /**
   * @summary 更新内容
   */
  const cmsControllerUpdateContent = (
    id: string,
    updateCmsContentDto: UpdateCmsContentDto,
  ) => {
    return customInstance<void>({
      url: `/cms/contents/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCmsContentDto,
    });
  };
  /**
   * @summary 删除内容
   */
  const cmsControllerDeleteContent = (id: string) => {
    return customInstance<void>({
      url: `/cms/contents/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 发布内容
   */
  const cmsControllerPublishContent = (id: string) => {
    return customInstance<void>({
      url: `/cms/contents/${id}/publish`,
      method: "POST",
    });
  };
  /**
   * @summary 取消发布内容
   */
  const cmsControllerUnpublishContent = (id: string) => {
    return customInstance<void>({
      url: `/cms/contents/${id}/unpublish`,
      method: "POST",
    });
  };
  /**
   * @summary 获取文章列表
   */
  const cmsControllerGetArticles = (
    params?: CmsControllerGetArticlesParams,
  ) => {
    return customInstance<void>({
      url: `/cms/articles`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取案例列表
   */
  const cmsControllerGetCases = (params?: CmsControllerGetCasesParams) => {
    return customInstance<void>({ url: `/cms/cases`, method: "GET", params });
  };
  /**
   * @summary 获取产品展示列表
   */
  const cmsControllerGetProductShowcases = (
    params?: CmsControllerGetProductShowcasesParams,
  ) => {
    return customInstance<void>({
      url: `/cms/product-showcases`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取人员介绍列表
   */
  const cmsControllerGetProfiles = (
    params?: CmsControllerGetProfilesParams,
  ) => {
    return customInstance<void>({
      url: `/cms/profiles`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取所有标签
   */
  const cmsControllerFindAllTags = () => {
    return customInstance<void>({ url: `/cms/tags`, method: "GET" });
  };
  /**
   * @summary 创建标签
   */
  const cmsControllerCreateTag = (createCmsTagDto: CreateCmsTagDto) => {
    return customInstance<void>({
      url: `/cms/tags`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCmsTagDto,
    });
  };
  /**
   * @summary 获取标签详情
   */
  const cmsControllerFindOneTag = (id: string) => {
    return customInstance<void>({ url: `/cms/tags/${id}`, method: "GET" });
  };
  /**
   * @summary 更新标签
   */
  const cmsControllerUpdateTag = (
    id: string,
    updateCmsTagDto: UpdateCmsTagDto,
  ) => {
    return customInstance<void>({
      url: `/cms/tags/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCmsTagDto,
    });
  };
  /**
   * @summary 删除标签
   */
  const cmsControllerDeleteTag = (id: string) => {
    return customInstance<void>({ url: `/cms/tags/${id}`, method: "DELETE" });
  };
  return {
    cmsControllerCreateContent,
    cmsControllerFindAllContents,
    cmsControllerFindOneContent,
    cmsControllerUpdateContent,
    cmsControllerDeleteContent,
    cmsControllerPublishContent,
    cmsControllerUnpublishContent,
    cmsControllerGetArticles,
    cmsControllerGetCases,
    cmsControllerGetProductShowcases,
    cmsControllerGetProfiles,
    cmsControllerFindAllTags,
    cmsControllerCreateTag,
    cmsControllerFindOneTag,
    cmsControllerUpdateTag,
    cmsControllerDeleteTag,
  };
};
export type CmsControllerCreateContentResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerCreateContent"]>>
>;
export type CmsControllerFindAllContentsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerFindAllContents"]>>
>;
export type CmsControllerFindOneContentResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerFindOneContent"]>>
>;
export type CmsControllerUpdateContentResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerUpdateContent"]>>
>;
export type CmsControllerDeleteContentResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerDeleteContent"]>>
>;
export type CmsControllerPublishContentResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerPublishContent"]>>
>;
export type CmsControllerUnpublishContentResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerUnpublishContent"]>
  >
>;
export type CmsControllerGetArticlesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerGetArticles"]>>
>;
export type CmsControllerGetCasesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerGetCases"]>>
>;
export type CmsControllerGetProductShowcasesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCms>["cmsControllerGetProductShowcases"]>
  >
>;
export type CmsControllerGetProfilesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerGetProfiles"]>>
>;
export type CmsControllerFindAllTagsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerFindAllTags"]>>
>;
export type CmsControllerCreateTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerCreateTag"]>>
>;
export type CmsControllerFindOneTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerFindOneTag"]>>
>;
export type CmsControllerUpdateTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerUpdateTag"]>>
>;
export type CmsControllerDeleteTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCms>["cmsControllerDeleteTag"]>>
>;
