/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  AssignDto,
  BatchAssignDto,
  CreateCustomerDto,
  CustomerControllerFindAllParams,
  UpdateCustomerDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getCustomers = () => {
  /**
   * @summary 创建客户
   */
  const customerControllerCreate = (createCustomerDto: CreateCustomerDto) => {
    return customInstance<void>({
      url: `/customers`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCustomerDto,
    });
  };
  /**
   * @summary 获取客户列表
   */
  const customerControllerFindAll = (
    params?: CustomerControllerFindAllParams,
  ) => {
    return customInstance<void>({ url: `/customers`, method: "GET", params });
  };
  /**
   * @summary 获取客户详情
   */
  const customerControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/customers/${id}`, method: "GET" });
  };
  /**
   * @summary 更新客户
   */
  const customerControllerUpdate = (
    id: string,
    updateCustomerDto: UpdateCustomerDto,
  ) => {
    return customInstance<void>({
      url: `/customers/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCustomerDto,
    });
  };
  /**
   * @summary 删除客户
   */
  const customerControllerRemove = (id: string) => {
    return customInstance<void>({ url: `/customers/${id}`, method: "DELETE" });
  };
  /**
   * @summary 分配单个客户
   */
  const customerControllerAssignOne = (id: string, assignDto: AssignDto) => {
    return customInstance<void>({
      url: `/customers/${id}/assign`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: assignDto,
    });
  };
  /**
   * @summary 批量分配客户
   */
  const customerControllerBatchAssign = (batchAssignDto: BatchAssignDto) => {
    return customInstance<void>({
      url: `/customers/batch-assign`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: batchAssignDto,
    });
  };
  /**
   * @summary 查询客户分配历史
   */
  const customerControllerGetAssignmentHistory = (id: string) => {
    return customInstance<void>({
      url: `/customers/${id}/assignment-history`,
      method: "GET",
    });
  };
  /**
   * @summary 查询客户跟进记录
   */
  const customerControllerGetFollowRecords = (id: string) => {
    return customInstance<void>({
      url: `/customers/${id}/follow-records`,
      method: "GET",
    });
  };
  return {
    customerControllerCreate,
    customerControllerFindAll,
    customerControllerFindOne,
    customerControllerUpdate,
    customerControllerRemove,
    customerControllerAssignOne,
    customerControllerBatchAssign,
    customerControllerGetAssignmentHistory,
    customerControllerGetFollowRecords,
  };
};
export type CustomerControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerCreate"]>
  >
>;
export type CustomerControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerFindAll"]>
  >
>;
export type CustomerControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerFindOne"]>
  >
>;
export type CustomerControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerUpdate"]>
  >
>;
export type CustomerControllerRemoveResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerRemove"]>
  >
>;
export type CustomerControllerAssignOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerAssignOne"]>
  >
>;
export type CustomerControllerBatchAssignResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCustomers>["customerControllerBatchAssign"]>
  >
>;
export type CustomerControllerGetAssignmentHistoryResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomers>["customerControllerGetAssignmentHistory"]
    >
  >
>;
export type CustomerControllerGetFollowRecordsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getCustomers>["customerControllerGetFollowRecords"]
    >
  >
>;
