/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import { customInstance } from "../api-client";

export const getDefault = () => {
  const healthControllerCheck = () => {
    return customInstance<void>({ url: `/health`, method: "GET" });
  };
  return {};
};
