/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { InitializeResultResponse, MenuGroupDto } from "../../models";

import { customInstance } from "../api-client";

export const getMenus = () => {
  /**
   * 根据用户角色过滤菜单，返回按 groupTitle 分组的菜单结构
   * @summary 获取当前用户的菜单树
   */
  const menuControllerGetUserMenus = () => {
    return customInstance<MenuGroupDto[]>({
      url: `/menus/user`,
      method: "GET",
    });
  };
  /**
   * 创建默认菜单结构，仅在首次运行时调用。已存在的菜单将被跳过。
   * @summary 初始化菜单数据
   */
  const menuControllerInitializeMenus = () => {
    return customInstance<InitializeResultResponse>({
      url: `/menus/initialize`,
      method: "POST",
    });
  };
  return { menuControllerGetUserMenus, menuControllerInitializeMenus };
};
export type MenuControllerGetUserMenusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMenus>["menuControllerGetUserMenus"]>>
>;
export type MenuControllerInitializeMenusResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getMenus>["menuControllerInitializeMenus"]>
  >
>;
