/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企智通SCRM API
 * 企智通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreatePermissionDto,
  CreateRoleDto,
  PermissionControllerFindAllPermissionsParams,
  UpdateRoleDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getPermissions = () => {
  /**
   * @summary 同步前端路由到菜单
   */
  const permissionControllerSyncMenus = (
    permissionControllerSyncMenusBody: string[],
  ) => {
    return customInstance<void>({
      url: `/permissions/sync-menus`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: permissionControllerSyncMenusBody,
    });
  };
  /**
   * @summary 获取菜单树
   */
  const permissionControllerGetMenuTree = () => {
    return customInstance<void>({ url: `/permissions/menus`, method: "GET" });
  };
  /**
   * @summary 获取菜单详情
   */
  const permissionControllerFindOneMenu = (id: string) => {
    return customInstance<void>({
      url: `/permissions/menus/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 更新菜单
   */
  const permissionControllerUpdateMenu = (id: string) => {
    return customInstance<void>({
      url: `/permissions/menus/${id}`,
      method: "PUT",
    });
  };
  /**
   * @summary 删除菜单
   */
  const permissionControllerRemoveMenu = (id: string) => {
    return customInstance<void>({
      url: `/permissions/menus/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 创建权限
   */
  const permissionControllerCreatePermission = (
    createPermissionDto: CreatePermissionDto,
  ) => {
    return customInstance<void>({
      url: `/permissions/permissions`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPermissionDto,
    });
  };
  /**
   * @summary 查询所有权限
   */
  const permissionControllerFindAllPermissions = (
    params: PermissionControllerFindAllPermissionsParams,
  ) => {
    return customInstance<void>({
      url: `/permissions/permissions`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取权限树
   */
  const permissionControllerFindPermissionTree = () => {
    return customInstance<void>({
      url: `/permissions/permissions/tree`,
      method: "GET",
    });
  };
  /**
   * @summary 获取权限详情
   */
  const permissionControllerFindOnePermission = (id: string) => {
    return customInstance<void>({
      url: `/permissions/permissions/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 更新权限
   */
  const permissionControllerUpdatePermission = (
    id: string,
    createPermissionDto: CreatePermissionDto,
  ) => {
    return customInstance<void>({
      url: `/permissions/permissions/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: createPermissionDto,
    });
  };
  /**
   * @summary 删除权限
   */
  const permissionControllerRemovePermission = (id: string) => {
    return customInstance<void>({
      url: `/permissions/permissions/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 创建角色
   */
  const permissionControllerCreateRole = (createRoleDto: CreateRoleDto) => {
    return customInstance<void>({
      url: `/permissions/roles`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createRoleDto,
    });
  };
  /**
   * @summary 查询所有角色
   */
  const permissionControllerFindAllRoles = () => {
    return customInstance<void>({ url: `/permissions/roles`, method: "GET" });
  };
  /**
   * @summary 查询单个角色
   */
  const permissionControllerFindOneRole = (id: string) => {
    return customInstance<void>({
      url: `/permissions/roles/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 更新角色
   */
  const permissionControllerUpdateRole = (
    id: string,
    updateRoleDto: UpdateRoleDto,
  ) => {
    return customInstance<void>({
      url: `/permissions/roles/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateRoleDto,
    });
  };
  /**
   * @summary 删除角色
   */
  const permissionControllerRemoveRole = (id: string) => {
    return customInstance<void>({
      url: `/permissions/roles/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 为角色分配权限
   */
  const permissionControllerAssignPermissionsToRole = (id: string) => {
    return customInstance<void>({
      url: `/permissions/roles/${id}/permissions`,
      method: "PUT",
    });
  };
  /**
   * @summary 获取用户的所有权限
   */
  const permissionControllerGetUserPermissions = (id: string) => {
    return customInstance<void>({
      url: `/permissions/users/${id}/permissions`,
      method: "GET",
    });
  };
  /**
   * @summary 为用户分配角色
   */
  const permissionControllerAssignRolesToUser = (id: string) => {
    return customInstance<void>({
      url: `/permissions/users/${id}/roles`,
      method: "PUT",
    });
  };
  /**
   * @summary 初始化超级管理员
   */
  const permissionControllerInitializeSuperAdmin = () => {
    return customInstance<void>({
      url: `/permissions/initialize-super-admin`,
      method: "POST",
    });
  };
  return {
    permissionControllerSyncMenus,
    permissionControllerGetMenuTree,
    permissionControllerFindOneMenu,
    permissionControllerUpdateMenu,
    permissionControllerRemoveMenu,
    permissionControllerCreatePermission,
    permissionControllerFindAllPermissions,
    permissionControllerFindPermissionTree,
    permissionControllerFindOnePermission,
    permissionControllerUpdatePermission,
    permissionControllerRemovePermission,
    permissionControllerCreateRole,
    permissionControllerFindAllRoles,
    permissionControllerFindOneRole,
    permissionControllerUpdateRole,
    permissionControllerRemoveRole,
    permissionControllerAssignPermissionsToRole,
    permissionControllerGetUserPermissions,
    permissionControllerAssignRolesToUser,
    permissionControllerInitializeSuperAdmin,
  };
};
export type PermissionControllerSyncMenusResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerSyncMenus"]
    >
  >
>;
export type PermissionControllerGetMenuTreeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerGetMenuTree"]
    >
  >
>;
export type PermissionControllerFindOneMenuResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerFindOneMenu"]
    >
  >
>;
export type PermissionControllerUpdateMenuResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerUpdateMenu"]
    >
  >
>;
export type PermissionControllerRemoveMenuResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerRemoveMenu"]
    >
  >
>;
export type PermissionControllerCreatePermissionResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerCreatePermission"]
    >
  >
>;
export type PermissionControllerFindAllPermissionsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPermissions
      >["permissionControllerFindAllPermissions"]
    >
  >
>;
export type PermissionControllerFindPermissionTreeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPermissions
      >["permissionControllerFindPermissionTree"]
    >
  >
>;
export type PermissionControllerFindOnePermissionResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerFindOnePermission"]
    >
  >
>;
export type PermissionControllerUpdatePermissionResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerUpdatePermission"]
    >
  >
>;
export type PermissionControllerRemovePermissionResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerRemovePermission"]
    >
  >
>;
export type PermissionControllerCreateRoleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerCreateRole"]
    >
  >
>;
export type PermissionControllerFindAllRolesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerFindAllRoles"]
    >
  >
>;
export type PermissionControllerFindOneRoleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerFindOneRole"]
    >
  >
>;
export type PermissionControllerUpdateRoleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerUpdateRole"]
    >
  >
>;
export type PermissionControllerRemoveRoleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerRemoveRole"]
    >
  >
>;
export type PermissionControllerAssignPermissionsToRoleResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPermissions
      >["permissionControllerAssignPermissionsToRole"]
    >
  >
>;
export type PermissionControllerGetUserPermissionsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPermissions
      >["permissionControllerGetUserPermissions"]
    >
  >
>;
export type PermissionControllerAssignRolesToUserResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getPermissions>["permissionControllerAssignRolesToUser"]
    >
  >
>;
export type PermissionControllerInitializeSuperAdminResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getPermissions
      >["permissionControllerInitializeSuperAdmin"]
    >
  >
>;
