/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateProductDto,
  CreateProductFlowDto,
  ProductControllerFindAllParams,
  ProductControllerFindFlowsParams,
  UpdateProductDto,
  UpdateProductFlowDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getProducts = () => {
  /**
   * @summary 创建产品
   */
  const productControllerCreate = (createProductDto: CreateProductDto) => {
    return customInstance<void>({
      url: `/products`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createProductDto,
    });
  };
  /**
   * @summary 获取产品列表
   */
  const productControllerFindAll = (
    params?: ProductControllerFindAllParams,
  ) => {
    return customInstance<void>({ url: `/products`, method: "GET", params });
  };
  /**
   * @summary 获取产品详情
   */
  const productControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/products/${id}`, method: "GET" });
  };
  /**
   * @summary 更新产品
   */
  const productControllerUpdate = (
    id: string,
    updateProductDto: UpdateProductDto,
  ) => {
    return customInstance<void>({
      url: `/products/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateProductDto,
    });
  };
  /**
   * @summary 删除产品
   */
  const productControllerRemove = (id: string) => {
    return customInstance<void>({ url: `/products/${id}`, method: "DELETE" });
  };
  /**
   * @summary 创建产品流程
   */
  const productControllerCreateFlow = (
    createProductFlowDto: CreateProductFlowDto,
  ) => {
    return customInstance<void>({
      url: `/products/flows`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createProductFlowDto,
    });
  };
  /**
   * @summary 获取产品流程列表
   */
  const productControllerFindFlows = (
    params: ProductControllerFindFlowsParams,
  ) => {
    return customInstance<void>({
      url: `/products/flows`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取产品流程详情
   */
  const productControllerFindFlow = (id: string) => {
    return customInstance<void>({
      url: `/products/flows/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 更新产品流程
   */
  const productControllerUpdateFlow = (
    id: string,
    updateProductFlowDto: UpdateProductFlowDto,
  ) => {
    return customInstance<void>({
      url: `/products/flows/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateProductFlowDto,
    });
  };
  /**
   * @summary 删除产品流程
   */
  const productControllerRemoveFlow = (id: string) => {
    return customInstance<void>({
      url: `/products/flows/${id}`,
      method: "DELETE",
    });
  };
  return {
    productControllerCreate,
    productControllerFindAll,
    productControllerFindOne,
    productControllerUpdate,
    productControllerRemove,
    productControllerCreateFlow,
    productControllerFindFlows,
    productControllerFindFlow,
    productControllerUpdateFlow,
    productControllerRemoveFlow,
  };
};
export type ProductControllerCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProducts>["productControllerCreate"]>>
>;
export type ProductControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProducts>["productControllerFindAll"]>
  >
>;
export type ProductControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProducts>["productControllerFindOne"]>
  >
>;
export type ProductControllerUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProducts>["productControllerUpdate"]>>
>;
export type ProductControllerRemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProducts>["productControllerRemove"]>>
>;
export type ProductControllerCreateFlowResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProducts>["productControllerCreateFlow"]>
  >
>;
export type ProductControllerFindFlowsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProducts>["productControllerFindFlows"]>
  >
>;
export type ProductControllerFindFlowResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProducts>["productControllerFindFlow"]>
  >
>;
export type ProductControllerUpdateFlowResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProducts>["productControllerUpdateFlow"]>
  >
>;
export type ProductControllerRemoveFlowResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProducts>["productControllerRemoveFlow"]>
  >
>;
