/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { ProductPackageControllerFindAllParams } from "../../models";

import { customInstance } from "../api-client";

export const getProductPackages = () => {
  /**
   * @summary 获取所有产品套餐
   */
  const productPackageControllerFindAll = (
    params: ProductPackageControllerFindAllParams,
  ) => {
    return customInstance<void>({
      url: `/product-packages`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 创建产品套餐
   */
  const productPackageControllerCreate = () => {
    return customInstance<void>({ url: `/product-packages`, method: "POST" });
  };
  /**
   * @summary 获取套餐详情
   */
  const productPackageControllerFindOne = (id: string) => {
    return customInstance<void>({
      url: `/product-packages/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 更新产品套餐
   */
  const productPackageControllerUpdate = (id: string) => {
    return customInstance<void>({
      url: `/product-packages/${id}`,
      method: "PUT",
    });
  };
  /**
   * @summary 删除产品套餐
   */
  const productPackageControllerRemove = (id: string) => {
    return customInstance<void>({
      url: `/product-packages/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 添加产品到套餐
   */
  const productPackageControllerAddProduct = (id: string) => {
    return customInstance<void>({
      url: `/product-packages/${id}/products`,
      method: "POST",
    });
  };
  /**
   * @summary 从套餐中移除产品
   */
  const productPackageControllerRemoveProduct = (
    id: string,
    productId: string,
  ) => {
    return customInstance<void>({
      url: `/product-packages/${id}/products/${productId}`,
      method: "DELETE",
    });
  };
  return {
    productPackageControllerFindAll,
    productPackageControllerCreate,
    productPackageControllerFindOne,
    productPackageControllerUpdate,
    productPackageControllerRemove,
    productPackageControllerAddProduct,
    productPackageControllerRemoveProduct,
  };
};
export type ProductPackageControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getProductPackages>["productPackageControllerFindAll"]
    >
  >
>;
export type ProductPackageControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getProductPackages>["productPackageControllerCreate"]
    >
  >
>;
export type ProductPackageControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getProductPackages>["productPackageControllerFindOne"]
    >
  >
>;
export type ProductPackageControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getProductPackages>["productPackageControllerUpdate"]
    >
  >
>;
export type ProductPackageControllerRemoveResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getProductPackages>["productPackageControllerRemove"]
    >
  >
>;
export type ProductPackageControllerAddProductResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getProductPackages
      >["productPackageControllerAddProduct"]
    >
  >
>;
export type ProductPackageControllerRemoveProductResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getProductPackages
      >["productPackageControllerRemoveProduct"]
    >
  >
>;
