/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type {
  CreateTriggerDto,
  RuleEngineControllerFindEnabledTriggersParams,
  RuleEngineControllerFindTriggersParams,
  RuleEngineControllerGetLogsParams,
  UpdateTriggerDto,
} from "../../models";

import { customInstance } from "../api-client";

export const getRules = () => {
  /**
   * @summary 创建触发器
   */
  const ruleEngineControllerCreateTrigger = (
    createTriggerDto: CreateTriggerDto,
  ) => {
    return customInstance<void>({
      url: `/rules/triggers`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createTriggerDto,
    });
  };
  /**
   * @summary 获取触发器列表
   */
  const ruleEngineControllerFindTriggers = (
    params: RuleEngineControllerFindTriggersParams,
  ) => {
    return customInstance<void>({
      url: `/rules/triggers`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取启用的触发器列表
   */
  const ruleEngineControllerFindEnabledTriggers = (
    params: RuleEngineControllerFindEnabledTriggersParams,
  ) => {
    return customInstance<void>({
      url: `/rules/triggers/enabled`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary 获取触发器详情
   */
  const ruleEngineControllerFindOneTrigger = (id: string) => {
    return customInstance<void>({
      url: `/rules/triggers/${id}`,
      method: "GET",
    });
  };
  /**
   * @summary 更新触发器
   */
  const ruleEngineControllerUpdateTrigger = (
    id: string,
    updateTriggerDto: UpdateTriggerDto,
  ) => {
    return customInstance<void>({
      url: `/rules/triggers/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateTriggerDto,
    });
  };
  /**
   * @summary 删除触发器
   */
  const ruleEngineControllerRemoveTrigger = (id: string) => {
    return customInstance<void>({
      url: `/rules/triggers/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 启用/禁用触发器
   */
  const ruleEngineControllerToggleTrigger = (id: string) => {
    return customInstance<void>({
      url: `/rules/triggers/${id}/toggle`,
      method: "PATCH",
    });
  };
  /**
   * @summary 手动执行规则
   */
  const ruleEngineControllerExecuteRule = (triggerId: string) => {
    return customInstance<void>({
      url: `/rules/execute/${triggerId}`,
      method: "POST",
    });
  };
  /**
   * @summary 获取执行日志
   */
  const ruleEngineControllerGetLogs = (
    params: RuleEngineControllerGetLogsParams,
  ) => {
    return customInstance<void>({ url: `/rules/logs`, method: "GET", params });
  };
  return {
    ruleEngineControllerCreateTrigger,
    ruleEngineControllerFindTriggers,
    ruleEngineControllerFindEnabledTriggers,
    ruleEngineControllerFindOneTrigger,
    ruleEngineControllerUpdateTrigger,
    ruleEngineControllerRemoveTrigger,
    ruleEngineControllerToggleTrigger,
    ruleEngineControllerExecuteRule,
    ruleEngineControllerGetLogs,
  };
};
export type RuleEngineControllerCreateTriggerResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRules>["ruleEngineControllerCreateTrigger"]>
  >
>;
export type RuleEngineControllerFindTriggersResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRules>["ruleEngineControllerFindTriggers"]>
  >
>;
export type RuleEngineControllerFindEnabledTriggersResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRules>["ruleEngineControllerFindEnabledTriggers"]
    >
  >
>;
export type RuleEngineControllerFindOneTriggerResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRules>["ruleEngineControllerFindOneTrigger"]
    >
  >
>;
export type RuleEngineControllerUpdateTriggerResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRules>["ruleEngineControllerUpdateTrigger"]>
  >
>;
export type RuleEngineControllerRemoveTriggerResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRules>["ruleEngineControllerRemoveTrigger"]>
  >
>;
export type RuleEngineControllerToggleTriggerResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRules>["ruleEngineControllerToggleTrigger"]>
  >
>;
export type RuleEngineControllerExecuteRuleResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRules>["ruleEngineControllerExecuteRule"]>
  >
>;
export type RuleEngineControllerGetLogsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRules>["ruleEngineControllerGetLogs"]>
  >
>;
