/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import { customInstance } from "../api-client";

export const get = () => {
  /**
   * @summary 获取产品的所有流程
   */
  const productFlowControllerFindByProduct = (productId: string) => {
    return customInstance<void>({
      url: `/product-flows/product/${productId}`,
      method: "GET",
    });
  };
  /**
   * @summary 获取流程详情
   */
  const productFlowControllerFindOne = (id: string) => {
    return customInstance<void>({ url: `/product-flows/${id}`, method: "GET" });
  };
  /**
   * @summary 更新流程
   */
  const productFlowControllerUpdate = (id: string) => {
    return customInstance<void>({ url: `/product-flows/${id}`, method: "PUT" });
  };
  /**
   * @summary 删除流程
   */
  const productFlowControllerRemove = (id: string) => {
    return customInstance<void>({
      url: `/product-flows/${id}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 创建产品流程
   */
  const productFlowControllerCreate = () => {
    return customInstance<void>({ url: `/product-flows`, method: "POST" });
  };
  /**
   * @summary 启用/禁用流程
   */
  const productFlowControllerToggle = (id: string) => {
    return customInstance<void>({
      url: `/product-flows/${id}/toggle`,
      method: "PUT",
    });
  };
  /**
   * @summary 添加节点到流程
   */
  const productFlowControllerAddNode = (id: string) => {
    return customInstance<void>({
      url: `/product-flows/${id}/nodes`,
      method: "POST",
    });
  };
  /**
   * @summary 更新节点
   */
  const productFlowControllerUpdateNode = (nodeId: string) => {
    return customInstance<void>({
      url: `/product-flows/nodes/${nodeId}`,
      method: "PUT",
    });
  };
  /**
   * @summary 删除节点
   */
  const productFlowControllerRemoveNode = (nodeId: string) => {
    return customInstance<void>({
      url: `/product-flows/nodes/${nodeId}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 创建流程执行记录
   */
  const productFlowControllerCreateExecution = () => {
    return customInstance<void>({
      url: `/product-flows/executions`,
      method: "POST",
    });
  };
  /**
   * @summary 获取流程执行记录
   */
  const productFlowControllerFindExecutions = () => {
    return customInstance<void>({
      url: `/product-flows/executions`,
      method: "GET",
    });
  };
  /**
   * @summary 更新执行状态
   */
  const productFlowControllerUpdateExecutionStatus = (executionId: string) => {
    return customInstance<void>({
      url: `/product-flows/executions/${executionId}/status`,
      method: "PUT",
    });
  };
  /**
   * @summary 获取待执行的流程节点
   */
  const productFlowControllerFindPendingNodes = (contractId: string) => {
    return customInstance<void>({
      url: `/product-flows/executions/pending/${contractId}`,
      method: "GET",
    });
  };
  return {
    productFlowControllerFindByProduct,
    productFlowControllerFindOne,
    productFlowControllerUpdate,
    productFlowControllerRemove,
    productFlowControllerCreate,
    productFlowControllerToggle,
    productFlowControllerAddNode,
    productFlowControllerUpdateNode,
    productFlowControllerRemoveNode,
    productFlowControllerCreateExecution,
    productFlowControllerFindExecutions,
    productFlowControllerUpdateExecutionStatus,
    productFlowControllerFindPendingNodes,
  };
};
export type ProductFlowControllerFindByProductResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof get>["productFlowControllerFindByProduct"]>
  >
>;
export type ProductFlowControllerFindOneResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["productFlowControllerFindOne"]>>
>;
export type ProductFlowControllerUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["productFlowControllerUpdate"]>>
>;
export type ProductFlowControllerRemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["productFlowControllerRemove"]>>
>;
export type ProductFlowControllerCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["productFlowControllerCreate"]>>
>;
export type ProductFlowControllerToggleResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["productFlowControllerToggle"]>>
>;
export type ProductFlowControllerAddNodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["productFlowControllerAddNode"]>>
>;
export type ProductFlowControllerUpdateNodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["productFlowControllerUpdateNode"]>>
>;
export type ProductFlowControllerRemoveNodeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["productFlowControllerRemoveNode"]>>
>;
export type ProductFlowControllerCreateExecutionResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof get>["productFlowControllerCreateExecution"]>
  >
>;
export type ProductFlowControllerFindExecutionsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof get>["productFlowControllerFindExecutions"]>
  >
>;
export type ProductFlowControllerUpdateExecutionStatusResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof get>["productFlowControllerUpdateExecutionStatus"]
    >
  >
>;
export type ProductFlowControllerFindPendingNodesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof get>["productFlowControllerFindPendingNodes"]>
  >
>;
