/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import { customInstance } from "../api-client";

export const get = () => {
  /**
   * @summary 获取所有系统配置
   */
  const systemConfigControllerFindAll = () => {
    return customInstance<void>({ url: `/system/config`, method: "GET" });
  };
  /**
   * @summary 获取公开配置（无需认证）
   */
  const systemConfigControllerFindPublic = () => {
    return customInstance<void>({
      url: `/system/config/public`,
      method: "GET",
    });
  };
  /**
   * @summary 获取基础配置（系统名称、Logo等）
   */
  const systemConfigControllerGetBasicConfig = () => {
    return customInstance<void>({ url: `/system/config/basic`, method: "GET" });
  };
  /**
   * @summary 获取单个配置
   */
  const systemConfigControllerFindOne = (key: string) => {
    return customInstance<void>({
      url: `/system/config/${key}`,
      method: "GET",
    });
  };
  /**
   * @summary 创建或更新配置
   */
  const systemConfigControllerUpsert = (key: string) => {
    return customInstance<void>({
      url: `/system/config/${key}`,
      method: "PUT",
    });
  };
  /**
   * @summary 删除配置
   */
  const systemConfigControllerRemove = (key: string) => {
    return customInstance<void>({
      url: `/system/config/${key}`,
      method: "DELETE",
    });
  };
  /**
   * @summary 批量更新配置
   */
  const systemConfigControllerBatchUpdate = () => {
    return customInstance<void>({
      url: `/system/config/batch`,
      method: "POST",
    });
  };
  return {
    systemConfigControllerFindAll,
    systemConfigControllerFindPublic,
    systemConfigControllerGetBasicConfig,
    systemConfigControllerFindOne,
    systemConfigControllerUpsert,
    systemConfigControllerRemove,
    systemConfigControllerBatchUpdate,
  };
};
export type SystemConfigControllerFindAllResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["systemConfigControllerFindAll"]>>
>;
export type SystemConfigControllerFindPublicResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof get>["systemConfigControllerFindPublic"]>
  >
>;
export type SystemConfigControllerGetBasicConfigResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof get>["systemConfigControllerGetBasicConfig"]>
  >
>;
export type SystemConfigControllerFindOneResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["systemConfigControllerFindOne"]>>
>;
export type SystemConfigControllerUpsertResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["systemConfigControllerUpsert"]>>
>;
export type SystemConfigControllerRemoveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["systemConfigControllerRemove"]>>
>;
export type SystemConfigControllerBatchUpdateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof get>["systemConfigControllerBatchUpdate"]>
  >
>;
