/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { LoginDto, RegisterDto } from "../../models";

import { customInstance } from "../api-client";

// 登录响应类型
export interface LoginResponseDto {
  access_token: string;
  user: {
    id: string;
    username: string;
    name: string;
    email?: string;
    phone?: string;
    avatar?: string;
    roles: Array<{ id: string; name: string; code: string }>;
  };
}

export const get = () => {
  /**
   * @summary 用户登录
   */
  const authControllerLogin = (loginDto: LoginDto) => {
    return customInstance<LoginResponseDto>({
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginDto,
    });
  };
  /**
   * @summary 用户注册
   */
  const authControllerRegister = (registerDto: RegisterDto) => {
    return customInstance<void>({
      url: `/auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: registerDto,
    });
  };
  /**
   * @summary 获取当前用户信息
   */
  const authControllerGetUserInfo = () => {
    return customInstance<LoginResponseDto['user']>({ url: `/auth/me`, method: "GET" });
  };
  return {
    authControllerLogin,
    authControllerRegister,
    authControllerGetUserInfo,
  };
};
export type AuthControllerLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["authControllerLogin"]>>
>;
export type AuthControllerRegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["authControllerRegister"]>>
>;
export type AuthControllerGetUserInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof get>["authControllerGetUserInfo"]>>
>;
