/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { LoginDto, LoginResponseDto, RegisterDto } from "@/models";

import { customInstance } from "../api-client";

export const get = () => {
  /**
   * @summary 用户登录
   */
  const authControllerLogin = (loginDto: LoginDto) => {
    return customInstance<LoginResponseDto>({
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginDto,
    });
  };
  /**
   * @summary 用户注册
   */
  const authControllerRegister = (registerDto: RegisterDto) => {
    return customInstance<void>({
      url: `/auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: registerDto,
    });
  };
  /**
   * @summary 获取当前用户信息
   */
  const authControllerGetUserInfo = () => {
    return customInstance<LoginResponseDto>({ url: `/auth/me`, method: "GET" });
  };
  return {
    authControllerLogin,
    authControllerRegister,
    authControllerGetUserInfo,
  };
};
