/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export type CmsControllerFindAllContentsContentType =
  (typeof CmsControllerFindAllContentsContentType)[keyof typeof CmsControllerFindAllContentsContentType];

export const CmsControllerFindAllContentsContentType = {
  ARTICLE: "ARTICLE",
  CASE_STUDY: "CASE_STUDY",
  PRODUCT_SHOWCASE: "PRODUCT_SHOWCASE",
  PROFILE: "PROFILE",
} as const;
