/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export type ContractControllerFindAllStatus =
  (typeof ContractControllerFindAllStatus)[keyof typeof ContractControllerFindAllStatus];

export const ContractControllerFindAllStatus = {
  UNPAID: "UNPAID",
  PARTIAL: "PARTIAL",
  PAID: "PAID",
} as const;
