/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 触发器类型
 */
export type CreateTriggerDtoType = typeof CreateTriggerDtoType[keyof typeof CreateTriggerDtoType];


export const CreateTriggerDtoType = {
  DATA_ADD: 'DATA_ADD',
  DATA_UPDATE: 'DATA_UPDATE',
  TIME_CONDITION: 'TIME_CONDITION',
  SCHEDULED: 'SCHEDULED',
} as const;
