/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 姓名 */
  name: string;
  /** 邮箱 */
  email?: string;
  /** 手机号 */
  phone?: string;
  /** 部门ID */
  departmentId?: string;
  /** 角色ID列表 */
  roleIds?: string[];
  /** 状态: 1启用 0禁用 */
  status?: number;
}
