/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export * from './createCustomerDto';
export * from './createFollowRecordDto';
export * from './customerControllerFindAllParams';
export * from './loginDto';
export * from './registerDto';
export * from './updateCustomerDto';