/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { LoginUserDto } from "./loginUserDto";

export interface LoginResponseDto {
  /** 访问令牌 */
  access_token: string;
  /** 用户信息 */
  user: LoginUserDto;
}
