/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 平台
 */
export type TestWebhookDtoPlatform =
  (typeof TestWebhookDtoPlatform)[keyof typeof TestWebhookDtoPlatform];

export const TestWebhookDtoPlatform = {
  wecom: "wecom",
  feishu: "feishu",
  dingtalk: "dingtalk",
} as const;
