/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface UpdateProductDto {
  /** 产品名称 */
  name?: string;
  /** 产品代码 */
  code?: string;
  /** 产品描述 */
  description?: string;
  /** 价格 */
  price?: number;
  /** 产品时间轴 */
  timeline?: string[];
}
