/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */
import type { UpdateTriggerDtoConditions } from './updateTriggerDtoConditions';
import type { UpdateTriggerDtoType } from './updateTriggerDtoType';

export interface UpdateTriggerDto {
  /** 触发器名称 */
  name?: string;
  /** 触发器代码 */
  code?: string;
  /** 触发器类型 */
  type?: UpdateTriggerDtoType;
  /** 实体类型 */
  entityType?: string;
  /** 是否启用 */
  enabled?: boolean;
  /** 条件列表 */
  conditions?: UpdateTriggerDtoConditions;
}
