/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export interface UpdateContractDto {
  /** 客户ID */
  customerId?: string;
  /** 产品ID */
  productId?: string;
  /** 合同金额 */
  amount?: number;
  /** 服务开始日期 */
  serviceStart?: string;
  /** 服务结束日期 */
  serviceEnd?: string;
  /** 备注 */
  remark?: string;
}
