/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

export type UsersControllerFindAllParams = {
/**
 * 页码
 */
page?: number;
/**
 * 每页数量
 */
pageSize?: number;
/**
 * 搜索关键词
 */
search?: string;
/**
 * 部门ID
 */
departmentId?: string;
/**
 * 状态: 1启用 0禁用
 */
status?: number;
/**
 * 角色ID
 */
roleId?: string;
};
