/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * 企账通SCRM API
 * 企账通SCRM系统API文档
 * OpenAPI spec version: 1.0
 */

/**
 * 状态: 1启用 0禁用
 */
export type UserEntityStatus =
  (typeof UserEntityStatus)[keyof typeof UserEntityStatus];

export const UserEntityStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
