export {
  userStatusSchema,
  userRoleSchema,
  userRoleWithRelationSchema,
  userDepartmentSchema,
  userBaseSchema,
  userSchema,
  createUserSchema,
  updateUserSchema,
  queryUserSchema,
  resetPasswordSchema,
  userStatusMap,
  getUserStatusLabel,
  type UserStatus,
  type UserRole,
  type UserRoleWithRelation,
  type UserDepartment,
  type UserBase,
  type User,
  type UpdateUserBase,
  type QueryUserParams,
  type ResetPassword,
  type UserListResponse,
} from './user.schema'

// Legacy exports for gradual migration (数字枚举版本)
export {
  userStatusLegacySchema,
  userSchemaLegacy,
  userBaseSchemaLegacy,
  createUserSchemaLegacy,
  updateUserSchemaLegacy,
  queryUserSchemaLegacy,
  toUserStatus,
  toUserStatusLegacy,
  userStatusLegacyMap,
  getUserStatusLabelLegacy,
  type UserStatusLegacy,
  type UserLegacy,
  type QueryUserParamsLegacy,
  type UserListResponseLegacy,
} from './user-legacy.schema'
