package mcp

// perm_map.go MCP 工具名 → HTTP API(path+method) 权限映射表。
//
// path 采用 Gin 路由格式(如 "/psi/purchase-orders/:id/stock-in"),与 sys_api 表及
// Casbin 策略一致,经 keyMatch2 匹配。method 为大写 HTTP 动词。
// 未收录的工具会被权限中间件默认拒绝(见 perm_check.go)。
//
// authOnlyTools 收录"仅需认证"的工具:其对应 HTTP 路由挂在 authenticated 组
// (登录即可用,如个人收件箱/公告流/库存查询),MCP 层保持一致——有合法身份即放行,
// 不走 Casbin。其余工具走 Casbin(角色需在后台分配对应 API 权限)。
//
// 维护:新增工具时必须同步在此登记,否则该工具对非超管用户不可用。

var toolPermMap = map[string]toolPerm{
	// ── CRM:联系人 ──
	"crm_contact_create": {"POST", "/crm/customers/:id/contacts"},
	"crm_contact_delete": {"DELETE", "/crm/contacts/:id"},
	"crm_contact_list":   {"GET", "/crm/customers/:id/contacts"},
	"crm_contact_update": {"PUT", "/crm/contacts/:id"},
	// ── CRM:合同 ──
	"crm_contract_create":          {"POST", "/crm/contracts"},
	"crm_contract_get":             {"GET", "/crm/contracts/:id"},
	"crm_contract_list":            {"GET", "/crm/contracts"},
	"crm_contract_payment_summary": {"GET", "/crm/contracts/:id/payment-summary"},
	"crm_contract_update":          {"PUT", "/crm/contracts/:id"},
	// ── CRM:合同模板 ──
	"crm_contract_template_create":    {"POST", "/crm/contract-templates"},
	"crm_contract_template_get":       {"GET", "/crm/contract-templates/:id"},
	"crm_contract_template_list":      {"GET", "/crm/contract-templates"},
	"crm_contract_template_update":    {"PUT", "/crm/contract-templates/:id"},
	"crm_contract_template_variables": {"GET", "/crm/contract-templates/variables"},
	// ── CRM:自定义字段 ──
	"crm_customfield_create": {"POST", "/crm/custom-fields"},
	"crm_customfield_delete": {"DELETE", "/crm/custom-fields/:id"},
	"crm_customfield_list":   {"GET", "/crm/custom-fields"},
	"crm_customfield_update": {"PUT", "/crm/custom-fields/:id"},
	// ── CRM:客户 ──
	"crm_customer_create":   {"POST", "/crm/customers"},
	"crm_customer_get":      {"GET", "/crm/customers/:id"},
	"crm_customer_list":     {"GET", "/crm/customers"},
	"crm_customer_pick":     {"POST", "/crm/customers/:id/pick"},
	"crm_customer_release":  {"POST", "/crm/customers/:id/release"},
	"crm_customer_transfer": {"POST", "/crm/customers/:id/transfer"},
	"crm_customer_update":   {"PUT", "/crm/customers/:id"},
	// ── CRM:查重/跟进 ──
	"crm_dedup":                  {"GET", "/crm/dedup"},
	"crm_followup_list":          {"GET", "/crm/follow-records/timeline"},
	"crm_followup_plan_create":   {"POST", "/crm/follow-plans"},
	"crm_followup_record_create": {"POST", "/crm/follow-records"},
	// ── CRM:线索 ──
	"crm_lead_convert":  {"POST", "/crm/leads/:id/convert"},
	"crm_lead_create":   {"POST", "/crm/leads"},
	"crm_lead_get":      {"GET", "/crm/leads/:id"},
	"crm_lead_list":     {"GET", "/crm/leads"},
	"crm_lead_pick":     {"POST", "/crm/leads/:id/pick"},
	"crm_lead_release":  {"POST", "/crm/leads/:id/release"},
	"crm_lead_transfer": {"POST", "/crm/leads/:id/transfer"},
	"crm_lead_update":   {"PUT", "/crm/leads/:id"},
	// ── CRM:商机 ──
	"crm_opportunity_change_stage": {"PUT", "/crm/opportunities/:id/stage"},
	"crm_opportunity_create":       {"POST", "/crm/opportunities"},
	"crm_opportunity_get":          {"GET", "/crm/opportunities/:id"},
	"crm_opportunity_list":         {"GET", "/crm/opportunities"},
	"crm_opportunity_update":       {"PUT", "/crm/opportunities/:id"},
	// ── CRM:回款 ──
	"crm_payment_plan_create":   {"POST", "/crm/contracts/:id/payment-plans"},
	"crm_payment_plan_list":     {"GET", "/crm/contracts/:id/payment-plans"},
	"crm_payment_record_create": {"POST", "/crm/contracts/:id/payment-records"},
	"crm_payment_record_list":   {"GET", "/crm/contracts/:id/payment-records"},
	// ── CRM:产品 ──
	"crm_product_create": {"POST", "/crm/products"},
	"crm_product_get":    {"GET", "/crm/products/:id"},
	"crm_product_list":   {"GET", "/crm/products"},
	"crm_product_update": {"PUT", "/crm/products/:id"},
	// ── CRM:售后工单 ──
	"crm_ticket_change_status": {"PUT", "/crm/tickets/:id/status"},
	"crm_ticket_create":        {"POST", "/crm/tickets"},
	"crm_ticket_get":           {"GET", "/crm/tickets/:id"},
	"crm_ticket_list":          {"GET", "/crm/tickets"},
	"crm_ticket_update":        {"PUT", "/crm/tickets/:id"},
	// ── Dashboard(挂在 /api 模块) ──
	"dashboard_attendance_summary":       {"GET", "/api/dashboard/attendance-summary"},
	"dashboard_contract_trend":           {"GET", "/api/dashboard/contract-trend"},
	"dashboard_customer_distribution":    {"GET", "/api/dashboard/customer-distribution"},
	"dashboard_employee_distribution":    {"GET", "/api/dashboard/employee-distribution"},
	"dashboard_finance_summary":          {"GET", "/api/dashboard/finance-summary"},
	"dashboard_finance_trend":            {"GET", "/api/dashboard/finance-trend"},
	"dashboard_headcount_trend":          {"GET", "/api/dashboard/headcount-trend"},
	"dashboard_lead_source_distribution": {"GET", "/api/dashboard/lead-source-distribution"},
	"dashboard_opportunity_funnel":       {"GET", "/api/dashboard/opportunity-funnel"},
	"dashboard_overview":                 {"GET", "/api/dashboard/overview"},
	"dashboard_sales_ranking":            {"GET", "/api/dashboard/sales-ranking"},
	"dashboard_sales_trend":              {"GET", "/api/dashboard/sales-trend"},
	"dashboard_sales_vs_purchase":        {"GET", "/api/dashboard/sales-vs-purchase"},
	"dashboard_stock_value_by_warehouse": {"GET", "/api/dashboard/stock-value-by-warehouse"},
	// ── 审批 ──
	"approval_approve":          {"POST", "/approval/actions/approve"},
	"approval_flow_create":      {"POST", "/approval/flows"},
	"approval_flow_enable":      {"PUT", "/approval/flows/:id/enable"},
	"approval_flow_get":         {"GET", "/approval/flows/:id"},
	"approval_flow_list":        {"GET", "/approval/flows"},
	"approval_flow_save_design": {"PUT", "/approval/flows/:id/design"},
	"approval_initiated_list":   {"GET", "/approval/initiated"},
	"approval_instance_get":     {"GET", "/approval/instances/:id"},
	"approval_processed_list":   {"GET", "/approval/processed"},
	"approval_push":             {"POST", "/approval/actions/push"},
	"approval_reject":           {"POST", "/approval/actions/reject"},
	"approval_revoke":           {"PUT", "/approval/instances/:id/revoke"},
	"approval_todo_list":        {"GET", "/approval/todos"},
	// ── CMS ──
	"cms_article_create":  {"POST", "/cms/articles"},
	"cms_article_get":     {"GET", "/cms/articles/:id"},
	"cms_article_list":    {"GET", "/cms/articles"},
	"cms_article_update":  {"PUT", "/cms/articles/:id"},
	"cms_category_create": {"POST", "/cms/categories"},
	"cms_category_delete": {"DELETE", "/cms/categories/:id"},
	// list 工具调的是 ListAll(对应 authenticated 组的 /categories/all),非管理端分页列表
	"cms_category_list":   {"GET", "/cms/categories/all"},
	"cms_category_update": {"PUT", "/cms/categories/:id"},
	"cms_page_create":     {"POST", "/cms/pages"},
	"cms_page_delete":     {"DELETE", "/cms/pages/:id"},
	"cms_page_get":        {"GET", "/cms/pages/:id"},
	"cms_page_list":       {"GET", "/cms/pages"},
	"cms_page_update":     {"PUT", "/cms/pages/:id"},
	"cms_tag_create":      {"POST", "/cms/tags"},
	"cms_tag_delete":      {"DELETE", "/cms/tags/:id"},
	// list 工具调的是 ListAll(对应 authenticated 组的 /tags/all),非管理端分页列表
	"cms_tag_list":        {"GET", "/cms/tags/all"},
	"cms_tag_update":      {"PUT", "/cms/tags/:id"},
	// ── 系统配置(站点/企业微信) ──
	"site_config_get":     {"GET", "/system/site-config"},
	"site_config_update":  {"PUT", "/system/site-config"},
	"wecom_config_create": {"POST", "/system/oauth-configs"},
	"wecom_config_enable": {"PUT", "/system/oauth-configs/:id/enable"},
	"wecom_config_list":   {"GET", "/system/oauth-configs"},
	"wecom_config_update": {"PUT", "/system/oauth-configs/:id"},
	// ── 系统管理(用户/角色/菜单/API/字典) ──
	"system_api_create":        {"POST", "/system/apis"},
	"system_api_delete":        {"DELETE", "/system/apis/:id"},
	"system_api_list":          {"GET", "/system/apis"},
	"system_dict_create":       {"POST", "/system/dicts"},
	"system_dict_delete":       {"DELETE", "/system/dicts/:id"},
	"system_dict_get":          {"GET", "/system/dicts/:id"},
	"system_dict_list":         {"GET", "/system/dicts"},
	"system_dict_update":       {"PUT", "/system/dicts/:id"},
	"system_menu_create":       {"POST", "/system/menus"},
	"system_menu_delete":       {"DELETE", "/system/menus/:id"},
	"system_menu_tree":         {"GET", "/system/menus/tree"},
	"system_menu_update":       {"PUT", "/system/menus/:id"},
	"system_role_assign_apis":  {"PUT", "/system/roles/:id/apis"},
	"system_role_assign_menus": {"PUT", "/system/roles/:id/menus"},
	"system_role_create":       {"POST", "/system/roles"},
	"system_role_delete":       {"DELETE", "/system/roles/:id"},
	"system_role_get":          {"GET", "/system/roles/:id"},
	"system_role_get_apis":     {"GET", "/system/roles/:id/apis"},
	"system_role_list":         {"GET", "/system/roles/all"},
	"system_role_update":       {"PUT", "/system/roles/:id"},
	"system_user_create":       {"POST", "/system/users"},
	"system_user_delete":       {"DELETE", "/system/users/:id"},
	"system_user_get":          {"GET", "/system/users/:id"},
	"system_user_list":         {"GET", "/system/users"},
	"system_user_update":       {"PUT", "/system/users/:id"},
	// ── HRM 只读 ──
	"hrm_attendance_clock_list": {"GET", "/hrm/attendance/clocks"},
	"hrm_attendance_summary":    {"GET", "/hrm/attendance/summary"},
	"hrm_department_list":       {"GET", "/hrm/departments"},
	"hrm_department_tree":       {"GET", "/hrm/departments/tree"},
	"hrm_employee_get":          {"GET", "/hrm/employees/:id"},
	"hrm_employee_list":         {"GET", "/hrm/employees"},
	"hrm_payroll_list":          {"GET", "/hrm/payroll"},
	"hrm_position_list":         {"GET", "/hrm/positions"},
	// ── HRM 写 ──
	"hrm_attendance_clock":            {"POST", "/hrm/attendance/clock"},
	"hrm_attendance_summary_generate": {"POST", "/hrm/attendance/summary/generate"},
	"hrm_candidate_create":            {"POST", "/hrm/candidates"},
	"hrm_candidate_delete":            {"DELETE", "/hrm/candidates/:id"},
	// HTTP 层无候选人详情路由,详情权限沿用列表 API(Casbin)
	"hrm_candidate_get":               {"GET", "/hrm/candidates"},
	"hrm_candidate_list":              {"GET", "/hrm/candidates"},
	"hrm_candidate_update":            {"PUT", "/hrm/candidates/:id"},
	"hrm_department_create":           {"POST", "/hrm/departments"},
	"hrm_department_delete":           {"DELETE", "/hrm/departments/:id"},
	"hrm_department_update":           {"PUT", "/hrm/departments/:id"},
	"hrm_employee_create":             {"POST", "/hrm/employees"},
	"hrm_employee_delete":             {"DELETE", "/hrm/employees/:id"},
	"hrm_employee_update":             {"PUT", "/hrm/employees/:id"},
	"hrm_job_create":                  {"POST", "/hrm/jobs"},
	"hrm_job_delete":                  {"DELETE", "/hrm/jobs/:id"},
	"hrm_job_get":                     {"GET", "/hrm/jobs/:id"},
	"hrm_job_list":                    {"GET", "/hrm/jobs"},
	"hrm_job_update":                  {"PUT", "/hrm/jobs/:id"},
	"hrm_leave_approve":               {"PUT", "/hrm/attendance/leaves/:id/approve"},
	"hrm_leave_create":                {"POST", "/hrm/attendance/leaves"},
	"hrm_overtime_approve":            {"PUT", "/hrm/attendance/overtimes/:id/approve"},
	"hrm_overtime_create":             {"POST", "/hrm/attendance/overtimes"},
	"hrm_payroll_confirm":             {"PUT", "/hrm/payroll/:id/confirm"},
	"hrm_payroll_generate":            {"POST", "/hrm/payroll/generate"},
	"hrm_payroll_mark_paid":           {"PUT", "/hrm/payroll/:id/paid"},
	"hrm_payroll_save_structure":      {"PUT", "/hrm/payroll/structure"},
	"hrm_performance_create":          {"POST", "/hrm/performances"},
	"hrm_performance_delete":          {"DELETE", "/hrm/performances/:id"},
	"hrm_performance_get":             {"GET", "/hrm/performances/:id"},
	"hrm_performance_list":            {"GET", "/hrm/performances"},
	"hrm_performance_review":          {"PUT", "/hrm/performances/:id/review"},
	"hrm_performance_self_review":     {"PUT", "/hrm/performances/:id/self-review"},
	"hrm_position_create":             {"POST", "/hrm/positions"},
	"hrm_position_delete":             {"DELETE", "/hrm/positions/:id"},
	"hrm_position_update":             {"PUT", "/hrm/positions/:id"},
	// ── PSI ──
	"psi_asset_create":              {"POST", "/psi/assets"},
	"psi_asset_delete":              {"DELETE", "/psi/assets/:id"},
	"psi_asset_get":                 {"GET", "/psi/assets/:id"},
	"psi_asset_list":                {"GET", "/psi/assets"},
	"psi_asset_update":              {"PUT", "/psi/assets/:id"},
	"psi_purchase_order_create":     {"POST", "/psi/purchase-orders"},
	"psi_purchase_order_delete":     {"DELETE", "/psi/purchase-orders/:id"},
	"psi_purchase_order_get":        {"GET", "/psi/purchase-orders/:id"},
	"psi_purchase_order_list":       {"GET", "/psi/purchase-orders"},
	"psi_purchase_order_stock_in":   {"POST", "/psi/purchase-orders/:id/stock-in"},
	"psi_purchase_order_update":     {"PUT", "/psi/purchase-orders/:id"},
	"psi_purchase_return_create":    {"POST", "/psi/purchase-returns"},
	"psi_purchase_return_get":       {"GET", "/psi/purchase-returns/:id"},
	"psi_purchase_return_list":      {"GET", "/psi/purchase-returns"},
	"psi_purchase_return_stock_out": {"POST", "/psi/purchase-returns/:id/stock-out"},
	"psi_sales_order_create":        {"POST", "/psi/sales-orders"},
	"psi_sales_order_delete":        {"DELETE", "/psi/sales-orders/:id"},
	"psi_sales_order_get":           {"GET", "/psi/sales-orders/:id"},
	"psi_sales_order_list":          {"GET", "/psi/sales-orders"},
	"psi_sales_order_stock_out":     {"POST", "/psi/sales-orders/:id/stock-out"},
	"psi_sales_order_update":        {"PUT", "/psi/sales-orders/:id"},
	"psi_sales_return_create":       {"POST", "/psi/sales-returns"},
	"psi_sales_return_get":          {"GET", "/psi/sales-returns/:id"},
	"psi_sales_return_list":         {"GET", "/psi/sales-returns"},
	"psi_sales_return_stock_in":     {"POST", "/psi/sales-returns/:id/stock-in"},
	"psi_stock_in_list":             {"GET", "/psi/stock-in-orders"},
	"psi_stock_in_order_create":     {"POST", "/psi/stock-in-orders"},
	"psi_stock_list":                {"GET", "/psi/stock"},
	"psi_stock_movements":           {"GET", "/psi/stock/movements"},
	"psi_stock_out_list":            {"GET", "/psi/stock-out-orders"},
	"psi_stock_out_order_create":    {"POST", "/psi/stock-out-orders"},
	"psi_supplier_create":           {"POST", "/psi/suppliers"},
	"psi_supplier_delete":           {"DELETE", "/psi/suppliers/:id"},
	"psi_supplier_get":              {"GET", "/psi/suppliers/:id"},
	"psi_supplier_list":             {"GET", "/psi/suppliers"},
	"psi_supplier_update":           {"PUT", "/psi/suppliers/:id"},
	"psi_warehouse_create":          {"POST", "/psi/warehouses"},
	"psi_warehouse_delete":          {"DELETE", "/psi/warehouses/:id"},
	"psi_warehouse_get":             {"GET", "/psi/warehouses/:id"},
	"psi_warehouse_list":            {"GET", "/psi/warehouses"},
	"psi_warehouse_update":          {"PUT", "/psi/warehouses/:id"},
	// ── 财务 ──
	"finance_account_create":    {"POST", "/finance/accounts"},
	"finance_account_list":      {"GET", "/finance/accounts"},
	"finance_balance_sheet":     {"GET", "/finance/reports/balance-sheet"},
	"finance_income_statement":  {"GET", "/finance/reports/income-statement"},
	"finance_invoice_create":    {"POST", "/finance/invoices"},
	"finance_invoice_list":      {"GET", "/finance/invoices"},
	"finance_receivable_create": {"POST", "/finance/receivables"},
	"finance_receivable_get":    {"GET", "/finance/receivables/:id"},
	"finance_receivable_list":   {"GET", "/finance/receivables"},
	"finance_receivable_settle": {"POST", "/finance/receivables/:id/settle"},
	"finance_voucher_confirm":   {"PUT", "/finance/vouchers/:id/confirm"},
	"finance_voucher_create":    {"POST", "/finance/vouchers"},
	"finance_voucher_list":      {"GET", "/finance/vouchers"},
	// ── 项目 ──
	"project_create":      {"POST", "/project/projects"},
	"project_delete":      {"DELETE", "/project/projects/:id"},
	"project_get":         {"GET", "/project/projects/:id"},
	"project_list":        {"GET", "/project/projects"},
	"project_task_create": {"POST", "/project/tasks"},
	"project_task_delete": {"DELETE", "/project/tasks/:id"},
	"project_task_list":   {"GET", "/project/tasks"},
	"project_task_status": {"PUT", "/project/tasks/:id/status"},
	"project_task_update": {"PUT", "/project/tasks/:id"},
	"project_update":      {"PUT", "/project/projects/:id"},
	// ── 知识库 ──
	"kb_category_create":   {"POST", "/kb/categories"},
	"kb_category_delete":   {"DELETE", "/kb/categories/:id"},
	"kb_category_list":     {"GET", "/kb/categories"},
	"kb_category_update":   {"PUT", "/kb/categories/:id"},
	"kb_document_create":   {"POST", "/kb/documents"},
	"kb_document_delete":   {"DELETE", "/kb/documents/:id"},
	"kb_document_get":      {"GET", "/kb/documents/:id"},
	"kb_document_list":     {"GET", "/kb/documents"},
	"kb_document_restore":  {"PUT", "/kb/documents/:id/versions/:versionId/restore"},
	"kb_document_update":   {"PUT", "/kb/documents/:id"},
	"kb_document_versions": {"GET", "/kb/documents/:id/versions"},
	// ── 网盘 ──
	"cloud_file_create":   {"POST", "/cloud/files"},
	"cloud_file_delete":   {"DELETE", "/cloud/files/:id"},
	"cloud_file_list":     {"GET", "/cloud/files"},
	"cloud_file_update":   {"PUT", "/cloud/files/:id"},
	"cloud_folder_create": {"POST", "/cloud/folders"},
	"cloud_usage":         {"GET", "/cloud/usage"},
	// ── 定时任务 ──
	"enterprise_job_create":   {"POST", "/enterprise/jobs"},
	"enterprise_job_delete":   {"DELETE", "/enterprise/jobs/:id"},
	"enterprise_job_get":      {"GET", "/enterprise/jobs/:id"},
	"enterprise_job_list":     {"GET", "/enterprise/jobs"},
	"enterprise_job_log_list": {"GET", "/enterprise/job-logs"},
	"enterprise_job_run":      {"POST", "/enterprise/jobs/:id/run"},
	"enterprise_job_update":   {"PUT", "/enterprise/jobs/:id"},
	// ── 公共基础设施(api 模块) ──
	"attachment_create": {"POST", "/api/attachments"},
	"attachment_delete": {"DELETE", "/api/attachments/:id"},
	"attachment_list":   {"GET", "/api/attachments"},
	"calendar":          {"GET", "/api/calendar"},
	"file_sign":         {"GET", "/api/file/sign"},
	"file_upload_sts":   {"GET", "/api/upload/sts"},
	// ── 办公自动化(oa) ──
	"oa_expense_create":             {"POST", "/oa/expenses"},
	"oa_expense_delete":             {"DELETE", "/oa/expenses/:id"},
	"oa_expense_get":                {"GET", "/oa/expenses/:id"},
	"oa_expense_list":               {"GET", "/oa/expenses"},
	"oa_expense_mark_paid":          {"POST", "/oa/expenses/:id/mark-paid"},
	"oa_expense_update":             {"PUT", "/oa/expenses/:id"},
	"oa_form_data_create":           {"POST", "/oa/form-data"},
	"oa_form_data_delete":           {"DELETE", "/oa/form-data/:id"},
	"oa_form_data_get":              {"GET", "/oa/form-data/:id"},
	"oa_form_data_list":             {"GET", "/oa/form-data"},
	"oa_form_data_update":           {"PUT", "/oa/form-data/:id"},
	"oa_form_template_create":       {"POST", "/oa/forms"},
	"oa_form_template_delete":       {"DELETE", "/oa/forms/:id"},
	"oa_form_template_get":          {"GET", "/oa/forms/:id"},
	"oa_form_template_list":         {"GET", "/oa/forms"},
	"oa_form_template_list_enabled": {"GET", "/oa/forms/enabled"},
	"oa_form_template_toggle":       {"PUT", "/oa/forms/:id/toggle"},
	"oa_form_template_update":       {"PUT", "/oa/forms/:id"},
	"oa_loan_create":                {"POST", "/oa/loans"},
	"oa_loan_delete":                {"DELETE", "/oa/loans/:id"},
	"oa_loan_get":                   {"GET", "/oa/loans/:id"},
	"oa_loan_list":                  {"GET", "/oa/loans"},
	"oa_loan_mark_repaid":           {"POST", "/oa/loans/:id/mark-repaid"},
	"oa_loan_update":                {"PUT", "/oa/loans/:id"},
	"oa_meeting_booking_create":     {"POST", "/oa/meeting-bookings"},
	"oa_meeting_booking_delete":     {"DELETE", "/oa/meeting-bookings/:id"},
	"oa_meeting_booking_get":        {"GET", "/oa/meeting-bookings/:id"},
	"oa_meeting_booking_list":       {"GET", "/oa/meeting-bookings"},
	"oa_meeting_booking_update":     {"PUT", "/oa/meeting-bookings/:id"},
	"oa_meeting_room_create":        {"POST", "/oa/meeting-rooms"},
	"oa_meeting_room_delete":        {"DELETE", "/oa/meeting-rooms/:id"},
	"oa_meeting_room_get":           {"GET", "/oa/meeting-rooms/:id"},
	"oa_meeting_room_list":          {"GET", "/oa/meeting-rooms"},
	"oa_meeting_room_update":        {"PUT", "/oa/meeting-rooms/:id"},
	"oa_message_get":                {"GET", "/oa/messages/:id"},
	"oa_message_inbox":              {"GET", "/oa/messages/inbox"},
	"oa_message_mark_read":          {"PUT", "/oa/messages/:id/read"},
	"oa_message_outbox":             {"GET", "/oa/messages/outbox"},
	"oa_message_read_all":           {"PUT", "/oa/messages/read-all"},
	"oa_message_send":               {"POST", "/oa/messages"},
	"oa_message_unread_count":       {"GET", "/oa/messages/unread-count"},
	"oa_notice_create":              {"POST", "/oa/notices"},
	"oa_notice_delete":              {"DELETE", "/oa/notices/:id"},
	"oa_notice_feed":                {"GET", "/oa/notices/feed"},
	"oa_notice_get":                 {"GET", "/oa/notices/:id"},
	"oa_notice_list":                {"GET", "/oa/notices"},
	"oa_notice_publish":             {"PUT", "/oa/notices/:id/publish"},
	"oa_notice_published":           {"GET", "/oa/notices/published"},
	"oa_notice_update":              {"PUT", "/oa/notices/:id"},
	"oa_notice_withdraw":            {"PUT", "/oa/notices/:id/withdraw"},
	"oa_schedule_calendar":          {"GET", "/oa/schedules/calendar"},
	"oa_schedule_create":            {"POST", "/oa/schedules"},
	"oa_schedule_delete":            {"DELETE", "/oa/schedules/:id"},
	"oa_schedule_get":               {"GET", "/oa/schedules/:id"},
	"oa_schedule_list":              {"GET", "/oa/schedules"},
	"oa_schedule_update":            {"PUT", "/oa/schedules/:id"},
	"oa_trip_create":                {"POST", "/oa/trips"},
	"oa_trip_delete":                {"DELETE", "/oa/trips/:id"},
	"oa_trip_get":                   {"GET", "/oa/trips/:id"},
	"oa_trip_list":                  {"GET", "/oa/trips"},
	"oa_trip_update":                {"PUT", "/oa/trips/:id"},
	"oa_work_log_create":            {"POST", "/oa/work-logs"},
	"oa_work_log_delete":            {"DELETE", "/oa/work-logs/:id"},
	"oa_work_log_get":               {"GET", "/oa/work-logs/:id"},
	"oa_work_log_list":              {"GET", "/oa/work-logs"},
	"oa_work_log_update":            {"PUT", "/oa/work-logs/:id"},
}

// authOnlyTools 收录"仅需认证"的工具(对应 HTTP authenticated 组,登录即可用)。
// 这些工具的 HTTP 路由本就不挂 CasbinRBAC(如个人收件箱/公告流/库存查询/BI 报表),
// MCP 层保持一致:有合法 API Key 身份即放行,不做 Casbin 校验。
var authOnlyTools = map[string]bool{
	// CRM/system 中挂在 authenticated 组的查询
	"crm_contract_payment_summary": true,
	"crm_dedup":                    true,
	"crm_followup_list":            true,
	"system_role_list":             true,
	"system_menu_tree":             true,
	// Dashboard(/api/dashboard/* 全在 authenticated 组)
	"dashboard_overview":                 true,
	"dashboard_opportunity_funnel":       true,
	"dashboard_sales_trend":              true,
	"dashboard_attendance_summary":       true,
	"dashboard_contract_trend":           true,
	"dashboard_customer_distribution":    true,
	"dashboard_employee_distribution":    true,
	"dashboard_finance_summary":          true,
	"dashboard_finance_trend":            true,
	"dashboard_headcount_trend":          true,
	"dashboard_lead_source_distribution": true,
	"dashboard_sales_ranking":            true,
	"dashboard_sales_vs_purchase":        true,
	"dashboard_stock_value_by_warehouse": true,
	// 审批的个人视角与操作(authenticated 组,本人可见即可操作)
	"approval_approve":        true,
	"approval_reject":         true,
	"approval_revoke":         true,
	"approval_push":           true,
	"approval_todo_list":      true,
	"approval_processed_list": true,
	"approval_initiated_list": true,
	"approval_instance_get":   true,
	// 站点配置(公开读取)/部门树/分类标签列表(authenticated 组)
	"site_config_get":     true,
	"hrm_department_tree": true,
	"cms_category_list":   true,
	"cms_tag_list":        true,
	// 库存查询(authenticated 组)
	"psi_stock_list":      true,
	"psi_stock_movements": true,
	// 网盘只读 + 知识库分类列表(authenticated 组)
	"cloud_file_list":  true,
	"cloud_usage":      true,
	"kb_category_list": true,
	// api 模块其余(attachments/calendar/file,均在 authenticated 组)
	"attachment_create": true,
	"attachment_delete": true,
	"attachment_list":   true,
	"calendar":          true,
	"file_sign":         true,
	"file_upload_sts":   true,
	// oa 个人视角/公告流/用户端表单(authenticated 组)
	"oa_message_inbox":              true,
	"oa_message_outbox":             true,
	"oa_message_unread_count":       true,
	"oa_message_get":                true,
	"oa_message_send":               true,
	"oa_message_mark_read":          true,
	"oa_message_read_all":           true,
	"oa_notice_feed":                true,
	"oa_notice_published":           true,
	"oa_notice_get":                 true,
	"oa_form_template_list_enabled": true,
}
