export {
  webhookPlatformSchema,
  webhookConfigBaseSchema,
  webhookConfigSchema,
  createWebhookConfigSchema,
  updateWebhookConfigSchema,
  sendWebhookSchema,
  testWebhookSchema,
  webhookPlatformMap,
  getWebhookPlatformLabel,
  type WebhookPlatform,
  type WebhookConfigBase,
  type WebhookConfig,
  type SendWebhook,
  type TestWebhook,
} from './webhook.schema'
